### ISSUE TITLE
Opening jupyter notebook done but UI doesn't know it

### ISSUE THREAD

**Issue by ivanistheone** [sagemathinc/smc#132] opened 2015-09-26 17:52 UTC
When I click New (+), Jupyter notebook, the notebook opens fine, but the UI continues to show Opening:

<img width="1060" alt="opening" src="https://cloud.githubusercontent.com/assets/163966/10118961/cb317a88-6455-11e5-936b-6f09f22fdef4.png">

Firefox on Mac

**Comment by williamstein** [comment] 2015-09-26 18:17
I can replicate this problem on Firefox OS X.  As a workaround until I fix it (and it shouldn't take long), you can try using Chrome (where Jupyter in SMC works fine).

**Comment by williamstein** [comment] 2015-09-27 00:39
This should be fixed via this patch:

  https://github.com/sagemathinc/smc/commit/667d17912f116ded75168167b7962d2c0857ec2a

**Closed by williamstein** 2015-09-27 00:39 UTC

**Comment by williamstein** [comment] 2015-09-27 00:44
Thanks for reporting this!  It was probably a problem for months (caused by
a weird change in Firefox who knows when) and was probably costing us a lot
of potential users!

On Saturday, September 26, 2015, Ivan Savov <notifications@github.com>
wrote:

> When I click New (+), Jupyter notebook, the notebook opens fine, but the
> UI continues to show Opening:
>
> [image: opening]
> <https://cloud.githubusercontent.com/assets/163966/10118961/cb317a88-6455-11e5-936b-6f09f22fdef4.png>
>
> Firefox on Mac
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/132>.
>


-- 
Sent from my massive iPhone 6 plus.
