### ISSUE TITLE
Clearing chat notification in bell by clicking the chatbox is not working anymore

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#937] opened 2016-09-25 00:13 UTC
This was implemented in https://github.com/sagemathinc/smc/pull/596.  Now that it doesn't seem to work anymore it is now a bug.

**Comment by haraldschilly** [comment] 2016-09-25 13:09
I just tested it, and it works.

What might be the issue is the following: was your cursor already in the box and focused? Maybe clicking again to re-focus doesn't trigger an event. only blurring and then focusing again causes it.

**Comment by williamstein** [comment] 2016-10-08 20:59
This does work. Closing.

**Closed by williamstein** 2016-10-08 20:59 UTC
Labels: A-sage chat, E-unclear, I-enhancement
