### ISSUE TITLE
block decrease indent behaves unexpectedly

### ISSUE THREAD

**Issue by mforets** [sagemathinc/smc#1952] opened 2017-05-12 10:08 UTC
in my browser at least (Google chrome Version 58.0.3029.110 (64-bit)), _decrease indentation of a block of code in the classical jupyter notebooks vs. the (new, default) SMC jupyter notebook behave differently_: either this is a bug or it's expected (since it could be useful in some cases), but in this case i didn't find keys for how to obtain the 'classic' behaviour : use SHIFT+TAB to decrease the whole selected block by 4 spaces and nothing more than that. 

an example follows: 
 
first In the classical jupyter notebook, paste:

```
def f(b):
    z = 0
    for i in xrange(1, b):
        z = z + i
    return z
```
then select the block and apply TAB, you'll get of course:
```
    def f(b):
        z = 0
        for i in xrange(1, b):
            z = z + i
        return z
```
select again and undo the operation by pressing SHIFT+TAB.

now, repeat but in the SMC jupyter notebook, where i'm getting:

```
def f(b):
    z = 0
    for i in xrange(1, b):
        z = z + i
        return z
```

**Comment by williamstein** [comment] 2017-05-16 15:35
I cannot reproduce this right now.  For me in the new SMC jupyter notebook shift+tab behaves properly.   Please re-open if you can reproduce this right now. 

@DrXyzzy -- you may want to check on this too.

**Comment by williamstein** [comment] 2017-05-16 15:37
Instead, if you see this, create a support request with a link to your notebook.  Maybe you have some tab characters or other funny characters in an input cell...

**Comment by DrXyzzy** [comment] 2017-05-16 15:48
Shift tab works the same in classic and modern notebooks with sublime keybindings. I'm able to reproduce the problem with default keybindings.

**Comment by williamstein** [comment] 2017-05-16 16:14
ok, now fixed properly.

**Closed** 2017-05-16 16:14 UTC
Labels: A-jupyter/ipython, E-easy, I-bug

**Comment by mforets** [comment] 2017-05-16 16:27
Thanks!
