### ISSUE TITLE
exception when closing a project ab

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1276] opened 2016-11-21 15:58 UTC
I know, it's not very informative, but just now I had the following exception when I tried to close a (stopped) project in SMC:

project 20e4a191-73ea-4921-80e9-0a5d792fc511

smc revision 4895a642e

```
Uncaught TypeError: undefined is not a function
    at Object.exports.path_split (smc-005f3c9….js?005f3c9…:11)
    at exports.filename_extension (smc-005f3c9….js?005f3c9…:11)
    at Object.exports.remove (smc-005f3c9….js?005f3c9…:52)
    at smc-005f3c9….js?005f3c9…:80
    at smc-005f3c9….js?005f3c9…:19
    at smc-005f3c9….js?005f3c9…:20
    at fe.iterate.ye.iterate (smc-005f3c9….js?005f3c9…:20)
    at he.__iterate (smc-005f3c9….js?005f3c9…:20)
    at n.i.__iterateUncached (smc-005f3c9….js?005f3c9…:19)
    at W (smc-005f3c9….js?005f3c9…:19)
    at n.T.__iterate (smc-005f3c9….js?005f3c9…:19)
```

**Comment by williamstein** [comment] 2016-11-21 15:59
Dupe of #1275

**Closed by williamstein** 2016-11-21 15:59 UTC
Labels: A-webapp
