### ISSUE TITLE
Have button for requesting access

### ISSUE THREAD

**Issue by timclemans206** [sagemathinc/smc#206] opened 2015-10-31 04:55 UTC
On Sage Days 70 wiki there's a link to https://cloud.sagemath.com/projects/ad9e7c84-b1de-4c64-b056-9a5e04d9107e/files/ would love to see a button for requesting access

**Comment by williamstein** [comment] 2016-09-23 18:11
Dupe of https://github.com/sagemathinc/smc/issues/637

**Closed by williamstein** 2016-09-23 18:11 UTC
