### ISSUE TITLE
make kernel of new jupyter notebooks a project wide setting

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#441] opened 2016-02-28 18:19 UTC
Wished by ivica here: https://groups.google.com/d/topic/sage-cloud/QImlZAZUQ1g/discussion

> It looks like jupyter notebook populates the kernel list simply by reading directories in the appropriate place. In Sagemath cloud case this seems to be /usr/local/share/jupyter/kernels. So the UI would just need to be populated with the values of display_name from kernel.js for each directory in /usr/local/share/jupyter/kernels
> Then the next step would be to set the variable MultiKernelManager.default_kernel_name to the name of the chosen kernel  (which is the name of the corresponding directory) in the file ~/.jupyter/jupyter_notebook_config.py.
> To take care of the renamed/deleted kernels, one option would be to check upyter_notebook_config.py file when starting the project and if the default kernel does not exists, simply delete the corresponding line from jupyter_notebook_config.py so that Jupyter falls back to the use of system-wide default kernel.
> 
> In Sagemath cloud all Jupyter kernels are listed in /usr/local/share/jupyter/kernels/ except SageMath 6.10, so perhaps the setting is a little bit more complicated than I thought.

**Comment by williamstein** [comment] 2016-02-28 18:57
1. Design: it would be nice to do this via a configuration file.  Then have the graphical UI simply be a way to edit this file. 

2. Does the Jupyter kernel have a command line option to set the default kernel?   If so, all we have to do is use the file from 1 in the `smc-jupyter` script.

**Comment by ssemigr** [comment] 2016-02-28 19:48
For 2, perhaps this would do the trick:
jupyter-notebook --MappingKernelManager.default_kernel_name='kernel_name'

**Comment by williamstein** [comment] 2017-01-08 02:08
Dupe of https://github.com/sagemathinc/smc/issues/424

**Closed by williamstein** 2017-01-08 02:08 UTC
Labels: A-jupyter/ipython, I-enhancement, I-feature request, M-low
