### ISSUE TITLE
characters added or deleted near cursor during edit with OS X and Firefox

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1771] opened 2017-03-10 20:06 UTC
Seen with Firefox 51.0.1 and 52.0 for the past 3 days, using OS X 10.11.6.

When typing into a file, occasionally (about once every 3 hours), characters are inserted or deleted near the cursor. The error is generally within about 10 characters of the cursor and may be behind or ahead of it. Sometimes continuing to type causes insertion of characters to alternate between actual and spurious cursor position. When characters are inserted, they are characters that have been typed within the past few seconds. Seen with .sagews, .md, and .txt files.

**Comment by williamstein** [comment] 2017-03-10 20:11
Can you include other info, e.g., that with your old Safari you see NaN in the timestamps in the history viewer?  However, I don't when viewing exactly the same history for the same file using the current safari version.

Also, you evidently have antivirus running on your computer (!? which?) and you said it ran when you noticed issues?  Maybe it is corrupting network traffic...?

Also, nobody else has ever once reported this exact problem, so if anybody has seen it, please report.

Finally, isn't it the case that if you refresh your browser then the problem vanishes for a while?

**Comment by DrXyzzy** [comment] 2017-03-13 16:59
- NaN in timetravel timestamp, and different last version number, were apparently a separate issue, resolved by upgrading Safari #1772 
- I uninstalled Avira and upgraded to MacOS 10.12.3 and still see cursor jumping with added/deleted characters in Firefox 52.0
- So far, I think the problem goes away when browser is refreshed. But refreshing only restores the currently open tab.

**Comment by williamstein** [comment] 2017-03-13 18:26
>  I think the problem goes away when browser is refreshed.

What about closing the file tab (and also history), then re-opening it?  (But not refreshing the browser.)

**Comment by DrXyzzy** [comment] 2017-03-14 00:14
Just happened again, and I looked at time travel in the FF tab where the bug was appearing. The last revision was indeed 1 higher than the last revision of time travel for same file in Safari. And the last revision in FF showed timestamp `about 5 hours from now, revision 271 (of 271)`. That sure looks as if a UTC time is being interpreted as local time:
```
# on local laptop
~ date +'%z +%Z'
-0500 +CDT
```

**Comment by DrXyzzy** [comment] 2017-03-14 00:37
Bug occurred again and this time there is NO extra last revision (last revision numbers match in time travel in FF and Safari) and no future timestamp in FF time travel revisions. Bug is cleared by closing and re-opening.

**Comment by williamstein** [comment] 2017-03-14 18:47
Now that I understand the root cause, this isn't really just firefox...

**Closed** 2017-03-15 00:43 UTC
Labels: A-firefox, A-frontend, A-sync, I-bug, M-blocker

**Comment by williamstein** [comment] 2017-03-15 00:50
time: 7 hours

process: while putting in the unit tests for the firefox-specific code, I observed a bizarre "corruption" of the file itself.  This was because "luckily" a patch containing exactly an ISO timestamp got created.... etc.  In any case, I chased this down and realized what I already knew, but hadn't thought about much, which is that the ISO regexp JSON code was very dangerous.  I then systematically fixed all this front to back, touching all parts of the  system -- browser, projects, hub backend, etc.   Then things broke horribly/obviously, since this is a lot of very subtle changes all over.  So after fixing some issues, I switched to using unit testing, and systematically ran the misc and hub unit tests... which uncovered many subtle issues.  I fixed them all, then testing the UI again, and now things seem good.  Will release later tonight.    I had no plans to work on this today or soon, but it took my whole day.
