### ISSUE TITLE
support Python library cv2

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1773] opened 2017-03-10 23:18 UTC
```
~$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02)
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
libdc1394 error: Failed to initialize libdc1394
>>> exit()
~$ python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50)
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
libdc1394 error: Failed to initialize libdc1394
>>> exit()
~$ python -m "import cv2"
/usr/bin/python: No module named import cv2
~$ python -c "import cv2"
libdc1394 error: Failed to initialize libdc1394
~$ python3 -c "import cv2"
libdc1394 error: Failed to initialize libdc1394
~$ sage -sh
 
Starting subshell with Sage environment variables set.  Don't forget
to exit when you are done.  Beware:
 * Do not do anything with other copies of Sage on your system.
 * Do not use this for installing Sage packages using "sage -i" or for
   running "make" at Sage's root directory.  These should be done
   outside the Sage shell.
 
Bypassing shell configuration files...
 
Note: SAGE_ROOT=/projects/sage/sage-7.5
(sage-sh) e92ac2f8ed554226ae47eeb07c8c0ab4@compute5-us:~$ python -m "import cv2"
/projects/sage/sage-7.5/local/bin/python: No module named import cv2
(sage-sh) e92ac2f8ed554226ae47eeb07c8c0ab4@compute5-us:~$ exit
Exited Sage subshell.
```

**Comment by haraldschilly** [comment] 2017-03-11 11:10
well, that "error" is a warning, essentially that in the VM there is no port of a usb webcam. besides that, the best way to use opencv is via the anaconda distribution.

your last test inside sage: `python -m "import cv2"` makes no sense :confused: 

I was curious if the problem is when it is being used. Below is a screenshot of

```
import numpy as np
import matplotlib.pyplot as plt
import cv2
img = cv2.imread('poles.png') # plotted in sage somewhere else ...

kernel = np.ones((5,5),np.float32)/25
dst = cv2.filter2D(img,-1,kernel)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))
_=ax1.imshow(img); _=ax1.set_title('Original')
_=ax2.imshow(dst); _=ax2.set_title('Averaging')
_=fig.tight_layout()
fig.show()
```

![smc-opencv-in-sagews-20170311](https://cloud.githubusercontent.com/assets/207405/23822756/9a8c8700-0653-11e7-9820-f814aee0ae75.png)

Therefore I'm closing this.

**Closed by haraldschilly** 2017-03-11 11:10 UTC
Labels: A-install, I-enhancement, I-software request
