### ISSUE TITLE
In file page, cursor should stay in terminal command text box after changing file directory

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#314] opened 2015-12-04 05:39 UTC
1) In an SMC project, view files and click on the terminal command textbox in the top right, and create a folder by typing "mkdir folder", and press enter (cursor stays in textbox)

2) Type "cd folder"

The cursor is now in the filename textbox in the top left corner of the screen (and you have no files in this folder!), instead of still being inside of the terminal command textbox, where you can easily return to your previous directory

**Comment by williamstein** [comment] 2015-12-04 05:47
This was a casualty of the react rewrite (it used to be like you describe), and I really wish things were like that again!  So I strongly agree with this.  Focus is frustrating in react.

**Comment by jlee27** [comment] 2015-12-04 19:57
This was caused by having the key of the file search component be the current path, which created a new ProjectFilesSearch component whenever the path changed, causing the "autoSelect"ed SearchInput to focus itself. Fixed in 87629e6159c5b6b88087be43ddd7ea19325ed790.

**Closed by jlee27** 2015-12-04 19:57 UTC
