### ISSUE TITLE
Start up all student projects on a schedule

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/smc#1637] opened 2017-02-01 21:56 UTC
I am a frequent user of the "start all student projects" button in the settings of a course. But better yet would be if I could schedule this operation to happen, say, 10 minutes before each of my class and section meetings!

**Comment by williamstein** [comment] 2017-02-01 22:09
Dupe of #437 -- which makes it even higher priority!

**Closed by williamstein** 2017-02-01 22:09 UTC
