### ISSUE TITLE
jupyter interact plots do not handle smc-blob images (sync issue)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#486] opened 2016-03-25 13:04 UTC
this is a fallout of sync2:
1. in an ipynb worksheet, enter this code in a cell:
   
   ```
   from ipywidgets import *
   import matplotlib.pyplot as plt
   %matplotlib inline
   @interact
   def f(k = (-10, 10)):
       plt.plot([k*x + 2 for x in range(-20, 20)])
   ```
   
   and open up this worksheet in two windows.
2. Then evaluate the cell in both windows
3. move the slider on both sides an watch the console for errors like this:

```
Uncaught (in promise) Error: Could not determine where the display message was from.  Widget will not be displayed(…)
data:image/png;base64,smc-blob::7dd5028c-42ee-4700-8bd7-e9b6df7dd8c9 Failed to load resource: net::ERR_INVALID_URL
```

which seems like there is yet another mechanism at play, that tries to update the resulting plot without knowing that it is in SMC land.

**Comment by williamstein** [comment] 2016-10-30 05:38
The problem is still here.  To fix will need to learn the message format that is used for interact (probably via some console.logs) and probably just somehow completely ignore them from the point of view of sync.  Not sure if this will be easy or not.

**Comment by williamstein** [comment] 2017-05-06 21:09
Closing in favor of https://github.com/sagemathinc/smc/issues/1930.  This is just going to be a test case.

**Closed by williamstein** 2017-05-06 21:09 UTC
Labels: A-jupyter/ipython, A-sync, E-hard, I-bug, M-low, P-low
