### ISSUE TITLE
Jupyter/IPython notebooks -- file uploaded but not updated in SMC

### ISSUE THREAD

**Issue by projetmbc** [sagemathinc/smc#96] opened 2015-09-02 07:41 UTC
Hello.

When playing with CSS animation in Jupyter makes me found a kind of bug (the IPython dev said that is a wanted feature indeed).

Then I have uploaded my file without this animations : see 

https://cloud.sagemath.com/projects/bcf4f485-52db-49db-ac8d-07e1b9b39795/files/sagemath_cloud_perso/isn/Term-S/main.ipynb

but I still see the bug. This is surely a cache problem because the file seems to not have been updated. I forgot to say that I have uploaded the same file but using a different name : see mmmmmain.ipynb . In that case I have the good version.

**Comment by williamstein** [comment] 2015-10-29 17:01
A temporary workaround is to delete the file `.<filename.ipynb>.syncdoc.*`, e.g., by typing `rm .<filename.ipynb>.syncdoc*` in the terminal or miniterminal.  

The root cause of the problem is that the sync system is supposed to check if `.<filename.ipynb>.syncdoc.*` is **Newer** than `filename.ipynb`, and if so, uses the new file.  If not, it uses the syncdoc file.   If you replace `filename.ipynb` by an older file, it isn't newer.   So instead it needs to store the last timestamp of `filename.ipynb` and if that changes (even to something older), revert to that.

**Comment by projetmbc** [comment] 2015-11-05 13:27
It seems that the problem appears when Jupiter is opened directly in the web browser rather than in the SMC interface. I have just met the problem now but I could fix it using by removing `<filename.ipynb>.syncdoc.*`.

**Comment by mforbes** [comment] 2016-02-03 19:40
I am still running into problems like this.  Even the workaround of deleting all `.syncdoc.*` and then `touch`ing my files to make sure they are new does not work.  I have created an example project demonstrating this issue:

* https://cloud.sagemath.com/projects/904ba7bf-3b02-4d7a-b6ee-c1a74a5b0e0b/files/clobber/Notes.ipynb

This really is a showstopper when trying to use version control as I risk completely clobbering collaborator's results, which makes them very unhappy...

**Comment by mforbes** [comment] 2016-03-15 20:36
One way to see this behaviour using only the GUI is:

* Create a new notebook `Test.ipynb`.
* Modify and save the notebook.
* Delete the notebook from the GUI.
* Create a new notebook with the same name `Test.ipynb`.

When opening the "new" notebook, the old content will still be in place.

**Comment by williamstein** [comment] 2016-09-06 18:55
This should definitely be fixed now.  Note that you have to open and close the file in the GUI.

**Closed by williamstein** 2016-09-06 18:55 UTC
Labels: A-jupyter/ipython, P-high
