### ISSUE TITLE
mode_name not defined

### ISSUE THREAD

**Issue by dimpase** [sagemathinc/smc#1755] opened 2017-03-08 10:05 UTC
After flipping between typeset and normal mode for a while, and removing some cells,
I have managed to get to the state where, unless there is an explicit `%typeset_mode ...`
in a cell, cell evaluation leads to
```
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/sage/sage-7.5/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 982, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-7.5/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1008, in execute_with_code_decorators
    code_decorators = [eval(code_decorator, self.namespace) for code_decorator in code_decorators]
  File "<string>", line 1, in <module>
NameError: name 'mode_name' is not defined
```

and, by the way, removing output cells seems to be a real problem, seems to have a lag of many seconds, and so removing too much (including the input!) all the time... pretty dreadful experience.

**Comment by dimpase** [comment] 2017-03-08 10:07
here is the link: https://cloud.sagemath.com/projects/e75eaca7-b6f1-4e62-b02d-a2eacf17ee1d/files/2017-03-08-084621.sagews

**Comment by DrXyzzy** [comment] 2017-03-08 16:28
To replicate, start a new .sagews and run the following two cells:
```
%typeset_mode True
%default_mode mode_name
%default_mode mode_name
%typeset_mode True
-- new cell
42
```

When you run the second cell, you will get `NameError: name 'mode_name' is not defined
`

Error state is cleared by doing
```
%default_mode sage
```

**Comment by williamstein** [comment] 2017-03-08 16:38
Isn't this 100% the expected behavior, since there is no mode called "mode_name"?  I think this should be closed.  What do you expect from doing

```
%default_mode some_made_up_random_nothing_blah
```

**Comment by williamstein** [comment] 2017-03-08 16:40
> and, by the way, removing output cells seems to be a real problem, seems to have a lag of many seconds, and so removing too much (including the input!) all the time... pretty dreadful experience.

How are you removing "output cells" (sage worksheets don't have cells -- just a line with output)?   
- I don't think it lags at all, and
- I don't think it removes to much.

**Comment by dimpase** [comment] 2017-03-08 16:41
I did not set any %delault_mode in a cell, although I did click on a button
so named. I certainly expected it to do something sane....

**Comment by williamstein** [comment] 2017-03-08 16:44
> I did not set any %default_mode in a cell

You did set a `%default_mode`.   The button evidently only inserts a template, and you have to actually change the mode.

We could make an issue to update the snippets menus.  We literally haven't touched them once since 2015, I think.

**Comment by dimpase** [comment] 2017-03-08 16:45
@williamstein : look at the worksheet I linked above and tell me how to remove lines 14-21. I have no clue, really. They seem to be leftovers of some sort.

**Comment by DrXyzzy** [comment] 2017-03-08 17:13
@dimpase to delete those lines (I am doing this in vim input mode):
- put cursor at end of line 12 (after `X`)
- highlight to start of line 23 (just before `%typeset...`)
- hit return once to delete and a second time to insert a blank line
- put cursor on the new blank line and hit ctrl-; (control semicolon) to break the cell

**Comment by dimpase** [comment] 2017-03-08 17:30
@DrXyzzy in vi(m), noone would remove lines in input mode. Instead `d` should do the job.

**Comment by williamstein** [comment] 2017-03-08 17:34
Closing in favor of #1760

**Closed by williamstein** 2017-03-08 17:34 UTC
Labels: A-sagews, I-bug

**Comment by DrXyzzy** [comment] 2017-03-08 18:09
time: 20 min
